### ISSUE TITLE
Errors regarding level db

### ISSUE THREAD

**Issue by markhaehnel** [derhuerst/hafas-record-delays#2]
I think there is some problem with the dependencies of this project. 

When using the following code i get an error that points me to something regarding level db.
```js
const createMonitor = require('hafas-monitor-departures')
const createHafas = require('db-hafas')
const recordDelays = require('hafas-record-delays')

const stations = ['008001841'] // array of station ids
const interval = 2 * 60 * 1000 // every two minutes

const hafas = createHafas('delay-tracker')
const monitor = createMonitor(hafas, stations, interval)

const recorder = recordDelays('./level-db.ldb', monitor)
recorder.on('error', console.error)
recorder.on('stats', console.log)
```

```
err props []
/Users/mhaehnel/Projects/delay-tracker/node_modules/hafas-record-delays/index.js:20
                dbVersion = dbVersion.toString('utf8')
                                      ^

TypeError: Cannot read property 'toString' of undefined
    at db.get (/Users/mhaehnel/Projects/delay-tracker/node_modules/hafas-record-delays/index.js:20:25)
    at /Users/mhaehnel/Projects/delay-tracker/node_modules/levelup/lib/levelup.js:164:14
    at /Users/mhaehnel/Projects/delay-tracker/node_modules/encoding-down/index.js:51:21
```

I tried it on Mac and Linux. Same problems.

**Comment by markhaehnel** [comment]
Just tried HEAD of the master branch. Checked the last commit and saw the change. Would be great if you could deploy that change to npm.

**Comment by derhuerst** [comment]
Did you use a new version of `hafas-record-delays` (`2`) with an old DB? You'll have to use `hafas-record-delays@1` or create a new DB.

**Comment by markhaehnel** [comment]
I had no database and created a new one. Commit 17e5b0dda430f085100cba824ed99fd2ef603ddb fixed the issue. That fix isn't in the NPM version.

**Comment by derhuerst** [comment]
I've found the issue an published `hafas-record-delays@2.0.1`. Please give that a try.

Keep in mind that `master` already contains a new implementation, as I've decided to use key prefixes instead of a single version entry.

**Comment by markhaehnel** [comment]
Works. Thank you for the quick response! 🚀

**Comment by derhuerst** [comment]
I'm curious: What are you planning to build with `hafas-record-delays`?

**Comment by markhaehnel** [comment]
I am moving soon and heared that the line with which I will drive to work is often delayed or cancelled.

With hafas-record-delays i will track the departures and based on my observations i will decide if i need to look into other ways to commute.

**Comment by derhuerst** [comment]
Which HAFAS endpoint do you intend to use? I've built [`record-vbb-delays`](https://npmjs.com/package/record-vbb-delays) a while ago (I still maintain it), it talks to the VBB endpoint. I should probably build a more generic tool.

**Comment by markhaehnel** [comment]
That project looks promising. I think it's sort of what i need. But i'm planning to use the DB endpoint.
If you're interested in building something more generic i'm glad to help you.

**Comment by derhuerst** [comment]
Sure. Otherwise forking `record-vbb-delays` and adapting it to the DB endpoint should be the most straightforward and pragmatic way to go for now.

**Comment by markhaehnel** [comment]
I will start working on a fork for DB to make myself comfortable with the codebase. Then we can talk about a generic approach.
